#!/usr/bin/env bash
# Display "best" school"

i=1
until [ $i > 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i+1))
done

